![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
ej_4 = np.arange(1,21)
ej_4 = ej_4.reshape(4,5)
print(ej_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [8]:
ej_4[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:
ej_4[:3:2,:5:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
ej_4[:-1,-1::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[x=="Loro"])
print(x)

['Loro' 'Loro']
['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


In [12]:
print(x[np.where(x == "Loro")])
print(x)

['Loro' 'Loro']
['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [13]:
ej_9 = np.arange(20)
print(ej_9)
ej_9_copy = ej_9.reshape(2,5,2).copy()
print(ej_9_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [14]:
print(ej_4)
print()
print(ej_4[-1::-1, -1::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [15]:
ej_11 = np.zeros(10)
print(ej_11)
print(ej_11.nbytes)

ej_11[3] = 1
print(ej_11)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [16]:
ej_12 = np.arange(10, 50)
print(ej_12)
print()
ej_12_2 = ej_12[-1::-1].copy()
print(ej_12_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [17]:
ej_13 = np.array((1,2,0,0,4,0))
print(ej_13)
indices = np.where(ej_13 != 0)
print(indices)

[1 2 0 0 4 0]
(array([0, 1, 4]),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [18]:
np.random.seed(1234)
ej_14 = np.random.randint(1000, size= (10,10))
print(ej_14)

mayor = ej_14.max()
menor = ej_14.min()

print(menor,mayor)

[[815 723 294  53 204 372 664 655 689 279]
 [233 154  30 683 158 748 892 794 374 442]
 [120 880 476 325 336 969 383 246 510 431]
 [562 752 763  76 293 802 934 506 195 743]
 [139 640 745 843 336   3 258 275 908 961]
 [459 371 619 465  14 243 455 828 490 619]
 [942 924  81 855 781 116 608 908 197 625]
 [991 997 671 761 601  84  45 528  41 840]
 [440 236 838 952  86 940 986 979 303 689]
 [ 18 597 686 482 805 365 806 135 996 707]]
3 997


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [19]:
ej_15 = np.random.randint(50, size = 30)
print(ej_15)
print(ej_15.mean())


[ 5 46 47 47 15 34 10 28  4 18 39 25 43 14 23 20 41  0 34 26 33 49 21  7
  4 39 17  0 21 41]
25.033333333333335


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
ej_16 = np.ones((5,5))
print(ej_16)
print()
ej_16[1:-1,1:-1] = 0
print(ej_16)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [21]:
ej_17 = np.ones((8,8))
print(ej_17)
print()
ej_17[::2,::2] = 0
ej_17[1::2,1::2] = 0
print(ej_17)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [22]:
ej_18 = np.array = [[0,1],[1,0]]
ej_18 = np.tile(ej_18, (4, 4))
print(ej_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [23]:
np.random.seed(1234)
ej_19 = np.random.randint(100, size=(5,5))
print(ej_19)
print()
ej_19 = (ej_19 - np.mean(ej_19)) / np.std(ej_19)
print(ej_19)

[[47 83 38 53 76]
 [24 15 49 23 26]
 [30 43 30 26 58]
 [92 69 80 73 47]
 [50 76 37 34 38]]

[[-0.07871658  1.60806734 -0.50041257  0.20241407  1.28008158]
 [-1.15638409 -1.57808007  0.01499363 -1.2032392  -1.06267387]
 [-0.87525344 -0.26613702 -0.87525344 -1.06267387  0.43668962]
 [ 2.02976333  0.95209582  1.46750202  1.13951625 -0.07871658]
 [ 0.06184874  1.28008158 -0.54726767 -0.687833   -0.50041257]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [24]:
ej_20 = np.arange(11)
print(ej_20)
ej_20_copia = ej_20.copy()
ej_20_copia[(ej_20_copia >= 3) & (ej_20_copia <= 8)] = -1
print()
print(ej_20_copia)
print()
ej_20_copia2 = ej_20_copia[ej_20_copia != -1].copy()
print(ej_20_copia2)


[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]

[ 0  1  2  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [2]:
import numpy as np

# 1.
tablero = np.full((10, 10), ' ')
print(tablero, end="\n\n")

# 2.
tablero[0:2, 1] = 'O'
tablero[1, 3:7] = 'O'

def recibir_disparo(fila:int, colum:int):
    if tablero[fila, colum] == " ":
        tablero[fila, colum] = "-"
    elif tablero[fila, colum] == "O":
        tablero[fila, colum] = "X"
    print(tablero, end="\n\n")

# 3.
recibir_disparo(4,5)
# 4.
recibir_disparo(1,3)

def posicionar_barco():
    colocado = False
    while not colocado:
        i = np.random.randint(10)
        j = np.random.randint(10)

        while (tablero[i,j] != " "):
            i = np.random.randint(10)
            j = np.random.randint(10)

        orientaciones = ["N","S","E","O"]

        while (len(orientaciones) > 0):
            orientacion = np.random.choice(orientaciones)
            match orientacion:
                case "N":
                    if (i >= 3):
                        if("O" not in tablero[i-3 : i+1, j]):
                            tablero[i-3 : i+1, j] = "O"
                            colocado = True
                            break
                case "S":
                    if (i <= 6):
                        if("O" not in tablero[i:i+4,j]):
                            tablero[i:i+4,j] = "O"
                            colocado = True
                            break
                case "E":
                    if (j <= 6):
                        if("O" not in tablero[i,j:j+4]):
                            tablero[i,j:j+4] = "O"
                            colocado = True
                            break
                case "O":
                    if (j >= 3):
                        if("O" not in tablero[i, j-3 : j+1]):
                            tablero[i, j-3 : j+1] = "O"
                            colocado = True
                            break
            
            orientaciones.remove(orientacion)

posicionar_barco()

print(tablero, end="\n\n")


[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'X' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '